---
- name: 'Ensure dependencies'
  ansible.builtin.package:
    name:
      - 'dnf-utils'
      - 'git'
      - 'rpm-build'
    state: 'present'

- name: 'Compose blueprint files from source'
  when: edge_compose_blueprint | bool
  block:
    - name: 'Ensure git checkout up to date'
      ansible.builtin.git:
        repo: "{{ edge_compose_blueprint_git_repo }}"
        dest: "{{ edge_compose_blueprint_checkout }}"
        version: "{{ edge_compose_blueprint_git_version }}"
        key_file: "{{ edge_compose_blueprint_git_sshkey | default(omit, true) }}"
        update: true
      register: 'git_repo_information'

    - name: 'Render blueprints and kickstart files'
      ansible.builtin.include_tasks: 'tasks/compose_blueprint.yml'
      loop: "{{ edge_compose_blueprint_images }}"
      loop_control:
        loop_var: 'blueprint'

- name: 'Build images with osbuild-composer'
  when: edge_compose_blueprint_build | bool
  ansible.builtin.include_tasks: 'tasks/make_blueprint.yml'
  loop: "{{ edge_compose_blueprint_images }}"
  loop_control:
    loop_var: 'image'
