---
- name: 'Ensure tempdir'
  ansible.builtin.file:
    path: '/var/cache/edge_result'
    state: 'directory'
    group: 'root'
    mode: '0700'
  changed_when: false  # The creation of this dir is not significant

- name: 'Import blueprint to osbuild-composer'
  infra.osbuild.push_blueprint:
    src: "/etc/osbuild-composer/blueprints/{{ image['name'] }}.toml"

- name: 'Check if this is an update of an existing image'
  ansible.builtin.stat:
    path: "/var/www/html/{{ image['name'] }}/repo"
  register: 'edge_image_repo'

- name: 'Build edge-commit'
  infra.osbuild.start_compose:
    blueprint: "{{ image['name'] }}"
    compose_type: 'edge-commit'
    ostree_ref: "{{ image['ref'] }}"
    ostree_url: "{{ (edge_image_repo['stat']['exists']) | ternary('http://localhost/' + image['name'] + '/repo', omit) }}"
  register: 'compose_start'

- name: 'Wait for osbuild-composer to compile image'
  infra.osbuild.wait_compose:
    compose_id: "{{ compose_start['result']['body']['build_id'] }}"
    timeout: "{{ edge_compose_blueprint_build_timeout * 60 }}"

- name: 'Download result'
  infra.osbuild.export_compose:
    compose_id: "{{ compose_start['result']['body']['build_id'] }}"
    dest: "/var/cache/edge_result/{{ compose_start['result']['body']['build_id'] }}-commit.tar"

- name: 'Ensure destination directory'
  ansible.builtin.file:
    path: "/var/www/html/{{ image['name'] }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Extract image to webserver'
  ansible.builtin.unarchive:
    src: "/var/cache/edge_result/{{ compose_start['result']['body']['build_id'] }}-commit.tar"
    dest: "/var/www/html/{{ image['name'] }}"
    remote_src: true
  when: not edge_image_repo['stat']['exists']

- name: 'Extract and apply update'
  when: edge_image_repo['stat']['exists']
  block:
    - name: 'Extract image'
      ansible.builtin.unarchive:
        src: "/var/cache/edge_result/{{ compose_start['result']['body']['build_id'] }}-commit.tar"
        dest: '/var/cache/edge_result'
        remote_src: true

    - name: 'Apply update to existing ostree on webserver'
      ansible.builtin.shell: |
        /usr/bin/ostree --repo=/var/www/html/{{ image['name'] }}/repo pull-local /var/cache/edge_result/repo
        /usr/bin/ostree summary --update --repo=/var/www/html/{{ image['name'] }}/repo
        /usr/sbin/restorecon -r /var/www/html/{{ image['name'] }}/repo
      changed_when: true

    - name: 'Delete completed build'
      ansible.builtin.command: /usr/bin/composer-cli compose delete {{ compose_start['result']['body']['build_id'] }}
      changed_when: true

- name: 'Ensure tempdir absent'
  ansible.builtin.file:
    path: '/var/cache/edge_result'
    state: 'absent'
  changed_when: false  # The deletion of this dir is not significant
